version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errcheck

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
