name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Go fmt (format code)
        run: go fmt ./...

      - name: Enforce formatting (gofmt -s)
        run: |
          set -euo pipefail
          fmt_out=$(gofmt -s -l .)
          if [ -n "$fmt_out" ]; then
            echo "The following files are not gofmt -s formatted:" >&2
            echo "$fmt_out" >&2
            echo "Run: gofmt -s -w ." >&2
            exit 1
          fi

      - name: Go vet (lint)
        run: go vet ./...

      - name: Go test
        run: go test ./...
